apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../kubernetes-web-lightclient

patches:
  - target:
      kind: Service
      name: kubernetes-web-lightclient
    patch: |-
      apiVersion: v1
      kind: Service
      metadata:
        name: kubernetes-web-lightclient
      spec:
        type: NodePort
